version: 2
updates:
- package-ecosystem: npm
  directory: "/probot-app"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: imgur
    versions:
    - 0.3.2
    - 1.0.0
  - dependency-name: bpmn-to-image
    versions:
    - 0.6.0
  - dependency-name: nock
    versions:
    - 13.0.11
    - 13.0.6
    - 13.0.9
  - dependency-name: probot
    versions:
    - 11.0.5
    - 11.0.6
    - 11.1.0
